### PR TITLE
✨ Add family relationship conformance resources

### LINKED ISSUE #21: NCPI Family Relationship
# Requester information
Please provide the following information:
Name: Eric Torstenson
Affiliation: VUMC (Vanderbilt)

# Request Details
Please provide the following information about what you wanting to accomplish with your model change request: 
Purpose: 
Our data will have maternal/paternal and twin IDs along with extended free text that will need to be captured in the data model. 

Who it benefits:
Any groups that work with Pedigree data

Use case: 
* Consider basic .ped file format where we have materinal_id/paternal_id columns which will need to be captured with a meaningful fhir configuration. 
* In addition to these most common forms, our dataset also has twin_id as well a couple of text fields to permit support for extended family as well.

### PR DESCRIPTION
**Pull request by liberaliscomputing**
This PR adds:

- a family relationship StructureDefinition resource;
- corresponding example resources

It also closes #21. 

Re @RobertJCarroll @allisonheath

### CODE REVIEW

**Review by torstees — DISMISSED** [review]
This looks fine to me.

**Comment by bwalsh** [comment]
https://terminology.hl7.org/1.0.0/CodeSystem-v3-RoleCode.html seems like a reasonable choice for ontology - given our desire to stay close to "stock" FHIR.

Things to think about:

* RoleCode seems to be a catch-all of misc roles e.g [ IncidentalServiceDeliveryLocationRoleType, OutpatientFacilityPracticeSetting, ..] that happens to hold some family relationships.
* Given we are scoping this to family relationship, is there a more specific ontology that might provide richer choices ?
* AnVIL family relationships in the raw data include : {'Husband or Wife', 'affected sibling', 'Unaffected Sibling', 'Brother or Sister in Law', 'father', 'father2', 'mother', 'Aunt or Uncle', 'Sibling', 'Other second degree relative', 'Parent', 'Identical Twin of Proband', 'Other 2nd Degree Relative', 'Sister', 'Other 4th degree relative', 'sibling', 'Son or Daughter', 'Son or Daughter-in-law', 'DZ twin', 'Other fifth degree relative', 'Nephew or Niece', 'Paternal Aunt or Uncle', 'First Cousin', 'Father', 'Other 3rd Degree Relative', 'Mother', 'Brother or Sister-in-law', 'Other 3rd degree relative', 'Other 2nd degree relative', 'Twin brother', 'Not related to the Proband', 'Affected', 'Cousin', 'Paternal Grandparent', 'Father1', 'Other forth degree relative', 'Other third degree relative', 'Maternal Aunt or Uncle', 'affected half-sib', 'Mother1', 'Not Related to the Proband', 'Brother or Sister', '#N/A', 'Affected2', 'ProbandBrother or Sister', 'brother', 'mother2/sister1', 'Other 4th Degree Relative', 'Brother', 'Brother or Sister-in-Law', 'sister2', 'Twin sister', 'Proband', 'Affected1', 'brother2', 'Other Not Related to Proband', 'affected twin', 'Maternal Grandparent', 'proband', 'Other not related to proband relative'}

**Comment by bwalsh** [comment]
It would be useful to document if we have considered a more specific model i.e:

* http://hl7.org/fhir/relatedperson.html
* http://hl7.org/fhir/valueset-relatedperson-relationshiptype.html

**Comment by liberaliscomputing** [comment]
> It would be useful to document if we have considered a more specific model i.e:
> 
>     * http://hl7.org/fhir/relatedperson.html
> 
>     * http://hl7.org/fhir/valueset-relatedperson-relationshiptype.html

- Re RelatedPerson, I've once considered this profile for modeling pedigree. By definition, however, 

> Information about a person that is involved in the care for a patient, but who is not the target of healthcare, nor has a formal responsibility in the care process.

- Re the ValueSet, this ValueSet is the combination of [contactRole2](https://terminology.hl7.org/1.0.0/CodeSystem-v2-0131.html) and [RoleCode](https://terminology.hl7.org/1.0.0/CodeSystem-v3-RoleCode.html). And `contactRole2` seems less relevant to our effort in modeling pedigree.

**Review by torstees — APPROVED** [review]

**Review by nicholasvk — APPROVED** [review]

**Pull request merged**
